### ISSUE TITLE
Testing my GitHub Skills

### ISSUE THREAD

**Issue by Ann-Tuity** [githubteacher/intro-github-April2016#173]
Jonathan?  Joe?  Do you read me?  @joe-tuity @jonathan-mtc
![ann and joe](https://cloud.githubusercontent.com/assets/18431460/14692515/f2875de8-0714-11e6-8bf5-5e9e9368819d.JPG)

**Comment by jonathan-mtc** [comment]
Awesome photo. I need a t shirt!
