### ISSUE TITLE
Please comment Here

### ISSUE THREAD

**Issue by githubteacher** [githubteacher/intro-github-April2016#2]
# Students will comment on this issue
- Once you are a collaborator
- [x] Everyone has been added

**Comment by maplegate** [comment]
so far so good

**Comment by hectorsector** [comment]
Please add me :)

**Comment by ghost** [comment]
Yay!

**Comment by jacob31** [comment]
Looks like it worked...

**Comment by ralphonz** [comment]
Nice!

**Comment by andrewiho** [comment]
Woo.

**Comment by ghost** [comment]
hello

**Comment by beardofedu** [comment]
commented

**Comment by cayelan** [comment]
hello!

**Comment by aaronvan** [comment]
Very good.

**Comment by JeansBolong** [comment]
Hello,

**Comment by chriswebb2309** [comment]
this is a comment

**Comment by apoorva89** [comment]
Hi there!

**Comment by manudmz** [comment]
Good morning ;)

**Comment by ghost** [comment]
Hey!

**Comment by lndgalante** [comment]
It works!

**Comment by NanashiExile** [comment]
Hello

**Comment by eastendwebsolutions** [comment]
new phone who dis

**Comment by 6axter82** [comment]
hello world!

**Comment by cnujjf11** [comment]
Happy Monday!

**Comment by xubenny** [comment]
I am commenting here

**Comment by oahernandez84** [comment]
Good

**Comment by lndgalante** [comment]
Hello world

**Comment by hectorsector** [comment]
hiya!

**Comment by mortezadianatfar** [comment]
Yay!`

**Comment by tamarasavage2** [comment]
Hello

**Comment by bensumali** [comment]
hello world!

**Comment by DanielDwyer** [comment]
Hello World!

**Comment by sash35** [comment]
Nice way to learn

**Comment by tc186026** [comment]
Hello!

**Comment by awakekat** [comment]
##Thanks for the class!

**Comment by happylil3** [comment]
:octocat: :wave:

**Comment by ashutoshbaghel** [comment]
Hey. Please add ##me

**Comment by JohnPoetzinger** [comment]
wahoo!

**Comment by argyleskull** [comment]
Hello githubteacher!

**Comment by ChristinaBj** [comment]
Hi!

**Comment by marnfed** [comment]
This is my comment.

**Comment by monikersupreme** [comment]
Howdy!

**Comment by parthivks** [comment]
Hello, all good to go

**Comment by RobAllison** [comment]
Hi

**Comment by dsahudev** [comment]
hi please add me !

**Comment by Grimbergen7** [comment]
Hello!

**Comment by vharsh** [comment]
#1 Commented.
`hello world`

**Comment by guti7** [comment]
ya se armó.

**Comment by Educ8dEar** [comment]
hello!

**Comment by rktaxali** [comment]
First comment from rkt. Thanks
1. Markdown: list
2. Markdown: list

**Comment by ykcor** [comment]
Hello GitHub!

**Comment by manudmz** [comment]
hello

**Comment by lsigle** [comment]
Hello Everyone!

**Comment by lndgalante** [comment]
Hola Mundo

**Comment by ajcairns** [comment]
### Hey!

Here's my comment

**Comment by markhollingsworth** [comment]
hello world

**Comment by tsarchdeacon** [comment]
OK, I git it

**Comment by gioz75** [comment]
- This is a test comment from Australia. 
- []Checking if i am a collaborator.

**Comment by woodd00** [comment]
# Hello!

**Looks good! :-)**
- 1
- 2

**Comment by mpaulisse** [comment]
Hello.

**Comment by DebeshNayak** [comment]
I am able to comment here.

**Comment by RandaKhairy** [comment]
Hello

# Hey

**Comment by scott7462** [comment]
hi

**Comment by rvernice** [comment]
I'm in and adding comments.
1. this seems easy enough

**Comment by shraddha-jain** [comment]
Hi

**Comment by qinli98** [comment]
hello

**Comment by gocarlitos** [comment]
cool!

**Comment by jacob31** [comment]
Hello

**Comment by chriswebb2309** [comment]
hello

**Comment by citizenkahn** [comment]
lgtm

**Comment by dsaldana91** [comment]
# Hi everyone

**Comment by xubenny** [comment]
- [x] checkbox?

**Comment by awakekat** [comment]
## Thanks for the class

the space is necessary after the 2 hashes

**Comment by shraddha-jain** [comment]
HI

**Comment by mitzifp** [comment]
Hello!

**Comment by argyleskull** [comment]
Hello!

**Comment by handsfreemc** [comment]
Good morning!

**Comment by lloftin** [comment]
> hello

**Comment by soupriya** [comment]
hi

**Comment by xubenny** [comment]
- [x] task1
- [x] task2
- [x] task3

**Comment by loupendley** [comment]
Looks great to me!

**Comment by DebeshNayak** [comment]
- Bullet point - 1
- Bullet point - 2

**Comment by iamdv** [comment]
Hello# 
1. LI 
- 1. UL

**Comment by githubteacher** [comment]
:tada: @maplegate, @halfaro1, @ddd, @jacob31, @ralphonz, @andrewiho, @cemopg, @beardofedu, @cayelan, @aaronvan, @JeansBolong, @chriswebb2309, @api1234, @alexdmz, @AnnaKNonE, @Fenwil, @NanashiExile, @eastendwebsolutions, @6axter82, @cnujjf11, @xubenny, @oahernandez84, @Fenwil, @halfaro1, @mortezadianatfar, @tamarasavage2, @bensumali, @DanielDwyer, @sash35, @tc186026, @awakekat, @happylil3, @ashutoshbaghel, @JohnPoetzinger, @argyleskull, @ChristinaBj, @marnfed, @monikersupreme, @parthivks, @RobAllison, @dsahudev, @Grimbergen7, @vharsh, @guti7, @Educ8dEar, @rktaxali, @ykcor, @alexdmz, @lsigle, @Fenwil, @ajcairns, @markhollingsworth, @tsarchdeacon, @gioz75, @woodd00, @mpaulisse, @DebeshNayak, @RandaKhairy, @scott7462, @rvernice, @shraddha-jain, @qinli98, @gocarlitos, @jacob31, @chriswebb2309, @citizenkahn, @dsaldana91, @xubenny, @awakekat, @shraddha-jain, @mitzifp, @argyleskull, @handsfreemc, @lloftin, @soupriya, and @xubenny are now  repository collaborators. :balloon:

**Comment by SoporteSn3** [comment]
hi there!!!

**Comment by Nada1996** [comment]
hello

**Comment by aftaba123** [comment]
Hello World

**Comment by yangos** [comment]
Hi there

**Comment by atabh1** [comment]
ok

**Comment by russellwhite** [comment]
Hello

**Comment by larrykavounas** [comment]
ok

**Comment by Tejendrdanand** [comment]
Hi There

Lets fix the bug

**Comment by AngelaReyes** [comment]
Hello

**Comment by githubteacher** [comment]
:tada: @lp110118, @iamdv, @SoporteSn3, @Nada1996, @aftaba123, @yangos, @atabh1, @russellwhite, @larrykavounas, and @Tejendrdanand are now  repository collaborators. :balloon:

**Comment by DebeshNayak** [comment]
# This is a header.

**Comment by tsarchdeacon** [comment]
Lots of emails coming in here...

**EDITED**

**Comment by Kingpinesse** [comment]
This is great

**Comment by rktaxali** [comment]
My Comment.

**Comment by aftaba123** [comment]
Hey Tango

**Comment by gsvineeth** [comment]
> Blah

**Comment by aurelioalv** [comment]
Hi

**Comment by ddshep** [comment]
Hello

**Comment by sinhaaman** [comment]
Hello

**Comment by katebolger** [comment]
Comment!

**Comment by mitzifp** [comment]
- [ ] done

**Comment by Benasdarbas** [comment]
### nice work, thank you

**Comment by bahaareh** [comment]
Hi

**Comment by DebeshNayak** [comment]
**This is bold text**
_This is italic text_

**Comment by githubteacher** [comment]
:tada: @AngelaReyes, @Kingpinesse, @gsvineeth, @aurelioalv, @ddshep, @sinhaaman, @katebolger, @Benasdarbas, and @bahaareh are now  repository collaborators. :balloon:

**Comment by amyheth** [comment]
dsfsdf

**Comment by DebeshNayak** [comment]
> This is a test

**Comment by aurelioalv** [comment]
This is Aurelio

**Comment by KellyBailey** [comment]
Got it.

**Comment by anandvip** [comment]
Ok

**Comment by phanimorampudi** [comment]
hello

**Comment by DebeshNayak** [comment]
`<?php
`

**Comment by danielbang** [comment]
finally

**Comment by maplegate** [comment]
How would you normally add collaborators?

**Comment by iamdv** [comment]
**Bold Text Test**

_Italic Test_

**Comment by phanimorampudi** [comment]
commented

**Comment by abhinaryanan** [comment]
good

**Comment by sanjusingh318** [comment]
hi there

**Comment by IanMartinUK** [comment]
Not so easy from a mobile!

**Comment by DebeshNayak** [comment]
`<?php
echo 1 + 2;
?>`

**Comment by barcod3** [comment]
Hi peeps

**Comment by jrpinto** [comment]
Hi everybody and SN3 friends!!

**Comment by loupendley** [comment]
**You need to verify your e-mail before you can post!**

**Comment by rtricoli101** [comment]
Hello

**Comment by Benasdarbas** [comment]
## nice work,  _Thank you_

**Comment by sisterneely** [comment]
Hello

**Comment by markcapodanno** [comment]
love issues!

**Comment by Extragarbage** [comment]
Comment

**Comment by mfk-refresh** [comment]
Hello

**Comment by johnnyxyz1223** [comment]
Hey. Finally. the email verification entry criteria is awkward

**Comment by Duir16** [comment]
Hi

**Comment by githubteacher** [comment]
:tada: @amyheth, @KellyBailey, @anandvip, @phanimpk, @danielbang, @phanimpk, @abhinaryanan, @sanjusingh318, @IanMartinUK, @barcod3, @jrpinto, @rtricoli101, @sisterneely, @markcapodanno, @Extragarbage, @Faisalndsu, @johnnyxyz1223, and @Duir16 are now  repository collaborators. :balloon:

**Comment by wanggith** [comment]
hi

**Comment by wsilva2525** [comment]
thanks

**Comment by githubhfan** [comment]
finally there!

**Comment by githubteacher** [comment]
:tada: @wanggith, @wsilva2525, and @githubhfan are now  repository collaborators. :balloon:

**Comment by bmannangi** [comment]
>>>test comment, test comment, test comment<<<

**Comment by i71186** [comment]
Just got it

**Comment by ogomezso** [comment]
commment

**Comment by cy4112016** [comment]
After I click watch, I receive a lot of email when other people become collaborator, how do I stop getting those email.

**Comment by weeksontheweb** [comment]
Yo!

**Comment by iamdv** [comment]
# BIO Page
- Name: DV
- Job: BI/JS Developer
- Favourite Language: JavaScript

**Comment by githubteacher** [comment]
:tada: @i71186, @ogomezso, @cy4112016, and @SatiredOut are now  repository collaborators. :balloon:

**Comment by Al-Johnson** [comment]
this is my first comment

**Comment by js185064** [comment]
comment

**Comment by TDylu8** [comment]
Please add me. Thanks.

**Comment by wsilva2525** [comment]
--[[  last online class
 how can get e recording fron last day class? --]]
