### ISSUE TITLE
handsfreemc Bio File

### ISSUE THREAD

**Issue by handsfreemc** [githubteacher/intro-github-April2016#20]
- **Name:** handsfreemc
- **Location:** I am from the city of angels - Los Angeles, CA.
- **Favorite Food:** Does _coffee_ qualify?

I love a good quote.

> "It is literally true that you can succeed best and quickest by helping others to succeed." _\- Napoleon Hill_

Have a wonderful week! :+1:

**Comment by JohnPoetzinger** [comment]
SoCal represent! Coffee in LA is a gourmet food for sure.
