### ISSUE TITLE
CEMOPG Bio File

### ISSUE THREAD

**Issue by ghost** [githubteacher/intro-github-April2016#39]
Name: Cassie
From: California
Food: Old Chicago Pizza (Chicago style pizza in northern California!)

I'm learning PHP!

**Comment by JohnPoetzinger** [comment]
Regents Pizza is the spot in San Diego if you are ever in town.

**Comment by katebolger** [comment]
Can't say that Chicago style pizza is my favorite...but would be happy to be in CA now!
