### ISSUE TITLE
Luigi's BIO file

### ISSUE THREAD

**Issue by loupendley** [githubteacher/intro-github-April2016#42]
# Github student lp110118 BIO
- Name:  Luigi Pendlini
- Location: San Diego, CA
- Favorite Food:  Vegan Lasagna
- Favorite Vacation spot: Puerto Vallarta, Mexico

By the way, this is not my real name, but a derivation of my name.

Tutti va bene!

**Comment by handsfreemc** [comment]
Well done! :+1:
