### ISSUE TITLE
Githubteacher Bio File 

### ISSUE THREAD

**Issue by githubteacher** [githubteacher/intro-github-April2016#6]
# Githubteacher Bio
- Name: GithubTeacher
- Location: Omaha, Nebraska
- Favorite Food: Jones Brother's Cupcakes

@halfaro1 ... Will you please :eyes: this issue for feedback?

**Comment by hectorsector** [comment]
👍

**Comment by larrykavounas** [comment]
Go Huskies

**Comment by aurelioalv** [comment]
We are catalonian and likes butifarra

**Comment by githubteacher** [comment]
@larrykavounas ... Go Huskers!!!

**Comment by danielbang** [comment]
greetings from Colombia

**Comment by Rosanne6** [comment]
Go Giants!

**Comment by tsarchdeacon** [comment]
**Name**: AGitHubUser
**Location**: I am coming from USA 
**Food**: Curry goat

**Comment by cnujjf11** [comment]
•Name: Github Student
•Location: Glen Allen, VA
•Favorite Food: Ice cream

**Comment by LinetteD** [comment]
San Diego ... Chocolate

**Comment by sanjusingh318** [comment]
Virginia....choclate cake

**Comment by DanielDwyer** [comment]
Thanks for leading this class!

**Comment by tc186026** [comment]
:cake:
