### ISSUE TITLE
#mortezadianatfar Bio File

### ISSUE THREAD

**Issue by mortezadianatfar** [githubteacher/intro-github-April2016#64]
# mortezadianatfar Bio File
- Name : Morteza
- Location : Tampere,Finland
- Interested : in Coding

**Comment by handsfreemc** [comment]
Happy coding! :computer:

**Comment by githubteacher** [comment]
@mortezadianatfar ... :heart: it ... looks great :tada:

**Comment by mortezadianatfar** [comment]
@githubteacher Thanks :)
